---
name: AGP

on:
  schedule:
    - cron: "0 * * * *" # hourly

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: AGP
        uses: [![AGP](https://github.com/tkjsmkn2bandung/javacode/actions/workflows/auto.yml/badge.svg?branch=main&event=push)](https://github.com/tkjsmkn2bandung/javacode/actions/workflows/auto.yml)
        with:
          token: ${{ secrets.CI_TOKEN }}
