---
name: AGP

on:
  schedule:
    - cron: "0 * * * *" # hourly

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: AGP
        uses: ms-jpq/auto-github-push/v1
        with: [![.github/workflows/auto.yml](https://github.com/tkjsmkn2bandung/javacode/actions/workflows/auto.yml/badge.svg?branch=main&event=pull_request_review)](https://github.com/tkjsmkn2bandung/javacode/actions/workflows/auto.yml)
          token: ${{ secrets.CI_TOKEN }}
